# Generated by Django 5.2.14 on 2026-06-04 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document', models.FileField(blank=True, upload_to='academic_calendar/')),
                ('document_url', models.URLField(blank=True)),
                ('academic_year', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-academic_year'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('arts', 'Arts'), ('science', 'Science'), ('commerce', 'Commerce & Management')], max_length=20)),
                ('hod_name', models.CharField(blank=True, max_length=150)),
                ('hod_photo', models.ImageField(blank=True, upload_to='dept/hod/')),
                ('hod_message', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('banner_image', models.ImageField(blank=True, upload_to='dept/banner/')),
                ('banner_image_url', models.URLField(blank=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='COPOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=200)),
                ('program_outcomes', models.TextField(help_text='Store as formatted text or comma-separated PO codes')),
                ('course_outcomes', models.TextField(help_text='List course outcomes')),
                ('mapping_matrix', models.TextField(blank=True, help_text='CO-PO mapping table as text')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copo_mappings', to='academics.department')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='dept/activities/')),
                ('date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='academics.department')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=200)),
                ('qualification', models.CharField(blank=True, max_length=300)),
                ('specialization', models.CharField(blank=True, max_length=300)),
                ('photo', models.ImageField(blank=True, upload_to='dept/faculty/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='academics.department')),
            ],
            options={
                'verbose_name': 'Department Faculty',
                'verbose_name_plural': 'Department Faculty',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('program_type', models.CharField(choices=[('ug', 'Undergraduate'), ('pg', 'Postgraduate'), ('diploma', 'Diploma'), ('cert', 'Certificate')], max_length=10)),
                ('duration', models.CharField(choices=[('1', '1 Year'), ('2', '2 Years'), ('3', '3 Years'), ('4', '4 Years'), ('5', '5 Years')], max_length=5)),
                ('eligibility', models.TextField(blank=True)),
                ('seats', models.IntegerField(default=0)),
                ('fee_per_year', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='academics.department')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='syllabus/')),
                ('academic_year', models.CharField(blank=True, max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='academics.department')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.program')),
            ],
            options={
                'verbose_name_plural': 'Syllabi',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
