# Generated by Django 4.2.7 on 2026-06-07 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dept/banner/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='academics.department')),
            ],
            options={
                'verbose_name': 'Department Banner',
                'verbose_name_plural': 'Department Banners',
                'ordering': ['order'],
            },
        ),
    ]
