# Generated by Django 4.2.7 on 2026-06-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_departmentbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='affiliation_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='introduced_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='seats',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
