# Generated by Django 4.2.7 on 2026-06-08 02:30

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_program_affiliation_status_program_introduced_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='departmentactivity',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description'),
        ),
    ]
