# Generated by Django 4.2.7 on 2026-06-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_department_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syllabus',
            options={'ordering': ['order', '-uploaded_at'], 'verbose_name_plural': 'Syllabi'},
        ),
        migrations.AddField(
            model_name='syllabus',
            name='document_url',
            field=models.URLField(blank=True, help_text='External URL for the syllabus document (used if no local file is uploaded)'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='document',
            field=models.FileField(blank=True, upload_to='syllabus/'),
        ),
    ]
