# Generated by Django 6.0.6 on 2026-07-02 08:58

from django.db import migrations, models


def seed_program_types(apps, schema_editor):
    ProgramType = apps.get_model('academics', 'ProgramType')
    defaults = [
        ('ug', 'Undergraduate', 'Undergraduate (UG)', 'fas fa-graduation-cap', 1),
        ('pg', 'Postgraduate', 'Postgraduate (PG)', 'fas fa-user-graduate', 2),
        ('diploma', 'Diploma', 'Diploma & Certificate', 'fas fa-scroll', 3),
        ('cert', 'Certificate', 'Certificate', 'fas fa-certificate', 4),
    ]
    for code, name, tab_label, icon, order in defaults:
        ProgramType.objects.update_or_create(
            code=code,
            defaults={
                'name': name,
                'tab_label': tab_label,
                'icon_class': icon,
                'order': order,
                'is_active': True,
                'show_in_tab': code != 'cert',
            },
        )


def convert_program_durations(apps, schema_editor):
    Program = apps.get_model('academics', 'Program')
    mapping = {
        '1': '1 Year',
        '2': '2 Years',
        '3': '3 Years',
        '4': '4 Years',
        '5': '5 Years',
    }
    for program in Program.objects.all():
        if program.duration in mapping:
            program.duration = mapping[program.duration]
            program.save(update_fields=['duration'])


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_syllabus_options_syllabus_document_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Short code stored on programs, e.g. ug, pg, diploma', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Label shown in admin when selecting a program type', max_length=100)),
                ('tab_label', models.CharField(help_text='Label shown on the programs page tab', max_length=120)),
                ('icon_class', models.CharField(default='fas fa-book', help_text='Font Awesome icon class for the programs page tab', max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('show_in_tab', models.BooleanField(default=True, help_text='Show this type as a separate tab on the programs page')),
            ],
            options={
                'verbose_name': 'Program Type',
                'verbose_name_plural': 'Program Types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g. 3 Years, 4 Semesters, 2 Years', max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(help_text='Program type code from Program Types', max_length=30),
        ),
        migrations.AlterField(
            model_name='program',
            name='seats',
            field=models.CharField(default='0', max_length=50, verbose_name='Total Seats'),
        ),
        migrations.RunPython(seed_program_types, migrations.RunPython.noop),
        migrations.RunPython(convert_program_durations, migrations.RunPython.noop),
    ]
