# Generated by Django 5.2.14 on 2026-06-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Admission Procedure', max_length=200)),
                ('content', models.TextField()),
                ('important_dates', models.TextField(blank=True)),
                ('documents_required', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admission Info',
                'verbose_name_plural': 'Admission Info',
            },
        ),
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('batch_year', models.IntegerField()),
                ('program', models.CharField(blank=True, max_length=200)),
                ('current_position', models.CharField(blank=True, max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('achievement', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='alumni/')),
                ('testimonial', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-batch_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('annual_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admission_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exam_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('academic_year', models.CharField(default='2024-25', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'ordering': ['order', 'program'],
            },
        ),
        migrations.CreateModel(
            name='LibraryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_books', models.IntegerField(default=0)),
                ('total_journals', models.IntegerField(default=0)),
                ('total_digital', models.IntegerField(default=0)),
                ('timing', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Library Info',
                'verbose_name_plural': 'Library Info',
            },
        ),
        migrations.CreateModel(
            name='LibraryResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('resource_type', models.CharField(choices=[('book', 'Book'), ('journal', 'Journal'), ('digital', 'Digital Resource'), ('thesis', 'Thesis'), ('magazine', 'Magazine')], max_length=20)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=150)),
                ('link', models.URLField(blank=True)),
                ('added_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Library Resource',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MeritListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=200)),
                ('medal_type', models.CharField(choices=[('gold', 'Gold Medal'), ('silver', 'Silver Medal'), ('bronze', 'Bronze Medal'), ('rank', 'University Rank')], max_length=50)),
                ('year', models.IntegerField()),
                ('rank', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Merit List Entry',
                'ordering': ['-year', 'student_name'],
            },
        ),
        migrations.CreateModel(
            name='OnlineAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('category', models.CharField(choices=[('GEN', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('program_applied', models.CharField(max_length=200)),
                ('last_exam_passed', models.CharField(max_length=100)),
                ('last_exam_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photo', models.ImageField(blank=True, upload_to='admissions/photos/')),
                ('signature', models.ImageField(blank=True, upload_to='admissions/signatures/')),
                ('marksheet', models.FileField(blank=True, upload_to='admissions/docs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Online Admission Application',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('eligibility', models.TextField()),
                ('amount', models.CharField(max_length=100)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
