# Generated by Django 4.2.7 on 2026-06-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeritListPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='University Merit List Settings', max_length=200)),
                ('show_poster', models.BooleanField(default=True, help_text='Toggle to hide or show the merit list poster/image on the page', verbose_name='Show Merit List Image')),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='merit_list/', verbose_name='Merit List Poster Image')),
                ('poster_image_url', models.URLField(blank=True, help_text='Use this for external URLs if no local image is uploaded', verbose_name='Poster Image URL (External)')),
            ],
            options={
                'verbose_name': 'Merit List Page Settings',
                'verbose_name_plural': 'Merit List Page Settings',
            },
        ),
    ]
