# Generated by Django 4.2.7 on 2026-06-08 14:38

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_meritlistpagesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructurePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Fee Structure Page Settings', max_length=200)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Rich text description/notes about the fee structure', verbose_name='Description')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fee Structure Page Settings',
                'verbose_name_plural': 'Fee Structure Page Settings',
            },
        ),
    ]
