# Generated by Django 4.2.7 on 2026-06-07 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_committee_slug_committeegalleryimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the custom page', max_length=200)),
                ('slug', models.SlugField(help_text='Unique URL path (e.g., science-club)', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Main description/introduction text (supports HTML)')),
                ('show_slider', models.BooleanField(default=True, verbose_name='Show Image Slider')),
                ('show_members', models.BooleanField(default=False, verbose_name='Show Member Listing')),
                ('show_activities', models.BooleanField(default=False, verbose_name='Show Activities')),
                ('show_events', models.BooleanField(default=False, verbose_name='Show Events (Imported from Happenings)')),
                ('show_gallery', models.BooleanField(default=False, verbose_name='Show Gallery Grid')),
                ('order', models.PositiveIntegerField(default=0, help_text='Sorting order in navigation/lists')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Page',
                'verbose_name_plural': 'Custom Pages',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CustomPageSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='custom_pages/slides/')),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='custom_pages.custompage')),
            ],
            options={
                'verbose_name': 'Custom Page Slider Image',
                'verbose_name_plural': 'Custom Page Slider Images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomPageMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, help_text='e.g. Coordinator, Committee Head, Member', max_length=150)),
                ('photo', models.ImageField(blank=True, upload_to='custom_pages/members/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='custom_pages.custompage')),
            ],
            options={
                'verbose_name': 'Custom Page Member',
                'verbose_name_plural': 'Custom Page Members',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomPageGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='custom_pages/gallery/')),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='custom_pages.custompage')),
            ],
            options={
                'verbose_name': 'Custom Page Gallery Image',
                'verbose_name_plural': 'Custom Page Gallery Images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomPageEventLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('happening', models.ForeignKey(help_text='Select a Happening to display on this page', on_delete=django.db.models.deletion.CASCADE, to='core.happening', verbose_name='Happening / Event')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='custom_pages.custompage')),
            ],
            options={
                'verbose_name': 'Custom Page Linked Event',
                'verbose_name_plural': 'Custom Page Linked Events',
                'ordering': ['order', '-happening__date'],
            },
        ),
        migrations.CreateModel(
            name='CustomPageActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, help_text='Upload a PDF or document attachment', upload_to='custom_pages/attachments/')),
                ('image', models.ImageField(blank=True, upload_to='custom_pages/activities/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='custom_pages.custompage')),
            ],
            options={
                'verbose_name': 'Custom Page Activity',
                'verbose_name_plural': 'Custom Page Activities',
                'ordering': ['order', '-date'],
            },
        ),
    ]
