# Generated by Django 4.2.7 on 2026-06-08 02:30

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('custom_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompage',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Main description/introduction text (supports HTML)', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='custompageactivity',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description'),
        ),
    ]
