# Generated by Django 4.2.7 on 2026-06-06 07:27

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='gallery_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video/Media'), ('news', 'News')], default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, upload_to=gallery.models.gallery_item_upload_path),
        ),
    ]
