# Generated by Django 4.2.7 on 2026-06-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryitem_gallery_type_alter_galleryitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerycategory',
            name='gallery_type',
        ),
    ]
