# Generated by Django 5.2.14 on 2026-06-04 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditationLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='accreditation/')),
                ('image_url', models.URLField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='achievements/')),
                ('image_url', models.URLField(blank=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BannerSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='banner/')),
                ('image_url', models.URLField(blank=True, help_text='Use this for external S3 URLs if no local image')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CollegeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('section', models.CharField(choices=[('about', 'About'), ('vision', 'Vision'), ('mission', 'Mission'), ('governance', 'Governance'), ('features', 'Distinctive Features')], max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'College Info Section',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ImportantLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('category', models.CharField(choices=[('important', 'Important Links'), ('quick', 'Quick Links')], default='important', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('principal', 'Principal'), ('director', 'Director/Founder'), ('vice_principal', 'Vice Principal'), ('chairman', 'Chairman')], max_length=30)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='leadership/')),
                ('message', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MarqueeNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marquee Notice',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('document', models.FileField(blank=True, upload_to='notices/')),
                ('document_url', models.URLField(blank=True)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document', models.FileField(blank=True, upload_to='policies/')),
                ('document_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Policies',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name_en', models.CharField(default='Chaitanya Science and Arts College', max_length=200)),
                ('college_name_hi', models.CharField(default='चैतन्य विज्ञान एवं कला महाविद्यालय, पामगढ़', max_length=200)),
                ('tagline', models.CharField(default="An Autonomous College, Approved by UGC | Accredited with Grade 'A' by NAAC", max_length=300)),
                ('address_line1', models.CharField(default='PAMGARH, JANJGIR-CHAMPA (C.G.), 495554', max_length=200)),
                ('address_line2', models.CharField(default='Affiliated to Shaheed Nandkumar Patel Vishwavidyalaya, Raigarh', max_length=200)),
                ('phone', models.CharField(default='+91-9425540666', max_length=20)),
                ('email', models.EmailField(default='chaitanyapamgarh@gmail.com', max_length=254)),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/ChaitanyaPamgarh/')),
                ('youtube_url', models.URLField(blank=True, default='https://www.youtube.com/@ChaitanyaCollegePamgarh')),
                ('instagram_url', models.URLField(blank=True)),
                ('google_maps_embed', models.TextField(blank=True)),
                ('established_year', models.IntegerField(default=2001)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='StatCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(help_text='e.g. 8000+', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=200)),
                ('role_in_committee', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.committee')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
