# Generated by Django 5.2.14 on 2026-06-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerGuidanceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100, verbose_name='First Name')),
                ('lname', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('msg', models.TextField(verbose_name='Message/Comments')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Career Guidance Submission',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('time', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(default='College Auditorium', max_length=200)),
                ('link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SocialScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='social_schemes/')),
                ('image_url', models.URLField(blank=True)),
                ('link', models.CharField(blank=True, help_text='e.g. social-schemes/1/index.html', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Social Scheme',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('program', models.CharField(help_text='e.g. M.Sc. Zoology (2022-23)', max_length=150)),
                ('rating', models.PositiveIntegerField(default=5, help_text='1 to 5 stars')),
                ('text', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='testimonials/')),
                ('photo_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'student_name'],
            },
        ),
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('latest', 'Latest'), ('exam', 'Exam'), ('admission', 'Admission'), ('students', 'Students')], default='latest', max_length=20),
        ),
    ]
