# Generated by Django 5.2.14 on 2026-06-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_careerguidancesubmission_event_socialscheme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Happening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='happenings/')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('link', models.CharField(blank=True, help_text='e.g. /event-details/148/index.html', max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Happening',
                'ordering': ['order', '-date'],
            },
        ),
    ]
