# Generated by Django 5.2.14 on 2026-06-04 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_happening'),
    ]

    operations = [
        migrations.AddField(
            model_name='happening',
            name='brochure',
            field=models.FileField(blank=True, help_text='Upload brochure or registration form (PDF)', null=True, upload_to='happenings/brochures/'),
        ),
        migrations.AddField(
            model_name='happening',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='happening',
            name='participants_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Participants'),
        ),
        migrations.AddField(
            model_name='happening',
            name='registration_link',
            field=models.URLField(blank=True, help_text='Link for registration (Google Form etc.)', max_length=500),
        ),
        migrations.CreateModel(
            name='HappeningImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='happenings/gallery/')),
                ('image_url', models.URLField(blank=True, help_text='External URL for image if not uploaded locally', max_length=500)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('happening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.happening')),
            ],
            options={
                'verbose_name': 'Happening Gallery Image',
                'verbose_name_plural': 'Happening Gallery Images',
                'ordering': ['order'],
            },
        ),
    ]
