# Generated by Django 5.2.14 on 2026-06-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_happening_brochure_happening_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='happening',
            name='banner_image_url',
            field=models.URLField(blank=True, help_text='Custom header banner image URL', max_length=500),
        ),
    ]
