# Generated by Django 4.2.7 on 2026-06-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_happening_banner_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLinkCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(help_text="e.g. 'students:merit_list' (Django name) or a relative path '/about/'", max_length=200)),
                ('icon', models.FileField(blank=True, help_text='Upload custom SVG/PNG icon. Falls back to 07.svg.', null=True, upload_to='icons/')),
                ('icon_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Quick Link Card',
                'verbose_name_plural': 'Quick Link Cards',
                'ordering': ['order', 'id'],
            },
        ),
    ]
