# Generated by Django 4.2.7 on 2026-06-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_quicklinkcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicklinkcard',
            name='bg_color',
            field=models.CharField(default='#ffffff', help_text='HEX color for card background, e.g. #ffffff or #B71A34', max_length=7),
        ),
        migrations.AddField(
            model_name='quicklinkcard',
            name='bg_image',
            field=models.ImageField(blank=True, help_text='Upload custom background image for the card.', null=True, upload_to='cards/'),
        ),
        migrations.AddField(
            model_name='quicklinkcard',
            name='overlay_color',
            field=models.CharField(default='#000000', help_text='HEX color for background overlay, e.g. #000000', max_length=7),
        ),
        migrations.AddField(
            model_name='quicklinkcard',
            name='overlay_opacity',
            field=models.FloatField(default=0.0, help_text='Overlay opacity between 0.0 (fully transparent) and 1.0 (fully opaque)'),
        ),
    ]
