# Generated by Django 4.2.7 on 2026-06-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_quicklinkcard_bg_color_quicklinkcard_bg_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicklinkcard',
            name='fa_icon',
            field=models.CharField(blank=True, help_text="FontAwesome icon class name, e.g. 'fa-graduation-cap', 'fa-building', 'fa-book-open'", max_length=100),
        ),
    ]
