# Generated by Django 4.2.7 on 2026-06-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_quicklinkcard_fa_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='About Chaitanya Science and Arts College', max_length=200)),
                ('breadcrumb_image', models.CharField(default='assets/images/banner/breadcrumb.png', max_length=300)),
                ('about_us_title', models.CharField(default='About Us', max_length=200)),
                ('about_us_description_1', models.TextField(default='')),
                ('about_us_description_2', models.TextField(default='')),
                ('about_us_description_3', models.TextField(default='')),
                ('about_us_image_url', models.CharField(default='https://chaitanyafiles01.s3.amazonaws.com/aboutImages/COLLEGE_BUILDING.jpg', max_length=500)),
                ('stat1_value', models.CharField(default='8000+', max_length=50)),
                ('stat1_label', models.CharField(default='Undergradute & Graduate Students', max_length=150)),
                ('stat1_icon', models.CharField(default='assets/images/icon/11.svg', max_length=150)),
                ('stat2_value', models.CharField(default='50+', max_length=50)),
                ('stat2_label', models.CharField(default='Chaitanya College Faculty and Staff', max_length=150)),
                ('stat2_icon', models.CharField(default='assets/images/icon/12.svg', max_length=150)),
                ('stat3_value', models.CharField(default='5000+', max_length=50)),
                ('stat3_label', models.CharField(default='Chaitanya College Alumni Worldwide', max_length=150)),
                ('stat3_icon', models.CharField(default='assets/images/icon/13.svg', max_length=150)),
                ('funfact1_value', models.CharField(default='90%', max_length=50)),
                ('funfact1_label', models.CharField(default='Graduate success rate', max_length=150)),
                ('funfact2_value', models.CharField(default='Top 10', max_length=50)),
                ('funfact2_label', models.CharField(default='Colleges in CG that Create Futures', max_length=150)),
                ('funfact3_value', models.CharField(default='No. 1', max_length=50)),
                ('funfact3_label', models.CharField(default='In Innovation & Entrepreneurship', max_length=150)),
                ('mission_statement', models.TextField(default='')),
                ('vision_title', models.CharField(default='Vision', max_length=100)),
                ('vision_text', models.TextField(default='')),
                ('mission_title', models.CharField(default='Mission', max_length=100)),
                ('mission_text_1', models.TextField(default='')),
                ('mission_text_2', models.TextField(default='')),
                ('governance_title', models.CharField(default='Governance', max_length=200)),
                ('governance_text', models.TextField(default='')),
                ('features_title', models.CharField(default='Distinctive Features of the College', max_length=200)),
                ('features_list', models.TextField(default='', help_text='Enter distinctive features, one per line')),
                ('testimonial_text', models.TextField(default='')),
                ('testimonial_author', models.CharField(default='VK Gupta', max_length=150)),
                ('testimonial_author_image', models.CharField(default='https://chaitanyafiles01.s3.amazonaws.com/aboutImages/vkgupta.png', max_length=500)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
    ]
