# Generated by Django 4.2.7 on 2026-06-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_aboutpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='testimonial_author_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
