# Generated by Django 4.2.7 on 2026-06-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_aboutpage_testimonial_author_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='recognition/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Recognition Document',
                'verbose_name_plural': 'Recognition Documents',
                'ordering': ['order', 'title'],
            },
        ),
    ]
