# Generated by Django 4.2.7 on 2026-06-07 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_recognition'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CommitteeGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='committees/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.committee')),
            ],
            options={
                'verbose_name': 'Committee Gallery Image',
                'verbose_name_plural': 'Committee Gallery Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='committees/activities/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.committee')),
            ],
            options={
                'verbose_name': 'Committee Activity',
                'verbose_name_plural': 'Committee Activities',
                'ordering': ['order', '-date'],
            },
        ),
    ]
