# Generated by Django 4.2.7 on 2026-06-07 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_committee_slug_committeegalleryimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
