# Generated by Django 4.2.7 on 2026-06-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_notice_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload event brochure/poster (300x200px recommended)', null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, help_text='External URL for brochure/poster if not uploaded locally'),
        ),
    ]
