# Generated by Django 4.2.7 on 2026-06-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_event_image_event_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='brochure',
            field=models.FileField(blank=True, help_text='Upload event brochure or registration details (PDF)', null=True, upload_to='events/brochures/'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the upcoming event'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, help_text='External URL for online registration (e.g. Google Form)', max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Optional YouTube video URL (watch link or short link)', max_length=500),
        ),
    ]
