# Generated by Django 4.2.7 on 2026-06-07 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_event_brochure_event_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UGCTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the custom table (e.g. UGC Files, Autonomy Grant Documents)', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sorting order of tables on the UGC page')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle table visibility on the front end')),
            ],
            options={
                'verbose_name': 'UGC Table',
                'verbose_name_plural': 'UGC Tables',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UGCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.PositiveIntegerField(default=1, help_text='Serial number inside the table', verbose_name='S.N.')),
                ('title', models.CharField(max_length=300, verbose_name='Name of the file/document')),
                ('file', models.FileField(blank=True, help_text='Upload local PDF/document', null=True, upload_to='ugc/documents/')),
                ('file_url', models.URLField(blank=True, help_text='External URL link (if not uploading local file)', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ugc_table', models.ForeignKey(help_text='Select the table this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.ugctable')),
            ],
            options={
                'verbose_name': 'UGC Document',
                'verbose_name_plural': 'UGC Documents',
                'ordering': ['sn', 'id'],
            },
        ),
    ]
