# Generated by Django 4.2.7 on 2026-06-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ugctable_ugcdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='UGCGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=200, verbose_name='Scheme / Funding Agency')),
                ('purpose', models.CharField(max_length=300, verbose_name='Purpose of Grant')),
                ('impact', models.CharField(max_length=300, verbose_name='Impact & Upgrades')),
                ('order', models.PositiveIntegerField(default=0, help_text='Sorting order of rows in the table')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this row from the table', verbose_name='Show in Table')),
            ],
            options={
                'verbose_name': 'UGC Grant / Funding Record',
                'verbose_name_plural': 'UGC Grant / Funding Records',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UGCPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='University Grants Commission (UGC) Recognition', max_length=200)),
                ('description', models.TextField(default='Chaitanya Science and Arts College is recognized under Sections 2(f) and 12(B) of the UGC Act, 1956. This recognition establishes our credibility as a premier institution of higher learning eligible for central assistance and academic development programs. The college is committed to maintaining high standards of education, research, and infrastructure as mandated by the UGC.')),
                ('show_ugc_details', models.BooleanField(default=True, help_text='Check to show the Autonomy, 2(f)/12(B), and Autonomy Benefits cards section', verbose_name='Show UGC Details Cards')),
                ('autonomy_status_title', models.CharField(default='Autonomous', max_length=150)),
                ('autonomy_status_subtitle', models.CharField(default='UGC Autonomous Status', max_length=150)),
                ('autonomy_status_text', models.TextField(default='Empowered to design its own curriculum, conduct examinations, and evaluate student performance.')),
                ('status_2f_12b_title', models.CharField(default='2(f) and 12(B) Status', max_length=150)),
                ('status_2f_12b_text', models.TextField(default='The recognition under Section 2(f) signifies that our college is a recognized higher education institution.\n\nThe Section 12(B) status makes the college eligible to receive developmental grants from the UGC and other central agencies for teaching, research, and infrastructure upgrades.')),
                ('benefits_title', models.CharField(default='Autonomy Benefits', max_length=150)),
                ('benefits_list', models.TextField(default='Modernized, industry-relevant curriculum.\nChoice-Based Credit System (CBCS).\nFaster result processing and publication.\nFocus on skill-based and vocational courses.', help_text='Enter one benefit per line')),
                ('show_grants_section', models.BooleanField(default=True, help_text='Check to show the UGC & Central Funding Support grants table', verbose_name='Show UGC & Central Funding Support Table')),
                ('grants_title', models.CharField(default='UGC & Central Funding Support', max_length=200)),
            ],
            options={
                'verbose_name': 'UGC Page Settings',
                'verbose_name_plural': 'UGC Page Settings',
            },
        ),
    ]
