# Generated by Django 4.2.7 on 2026-06-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_ugcgrant_ugcpagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='college_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='College Logo (Header/Footer)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='college_logo_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Mobile Logo'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo2',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo 2 (NAAC A)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo3',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo 3'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo4',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo 4'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo5',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo 5'),
        ),
    ]
