# Generated by Django 4.2.7 on 2026-06-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sitesettings_college_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='marquee_flag',
            field=models.CharField(blank=True, help_text="Custom text to highlight in the marquee (e.g. 'NEW', 'URGENT')", max_length=50, null=True, verbose_name='Marquee Flag (Optional)'),
        ),
        migrations.AddField(
            model_name='notice',
            name='show_in_marquee',
            field=models.BooleanField(default=False, verbose_name='Show in Marquee'),
        ),
    ]
