# Generated by Django 4.2.7 on 2026-06-08 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_program_affiliation_status_program_introduced_year_and_more'),
        ('core', '0019_notice_marquee_flag_notice_show_in_marquee'),
    ]

    operations = [
        migrations.AddField(
            model_name='happening',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='happenings', to='academics.department', verbose_name='Department'),
        ),
    ]
