# Generated by Django 4.2.7 on 2026-06-08 02:30

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_happening_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Detailed description of the upcoming event', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='happening',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description'),
        ),
    ]
