# Generated by Django 4.2.7 on 2026-06-08 02:38

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_event_description_alter_happening_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='about_us_description_1',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='About Us Description 1'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_us_description_2',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='About Us Description 2'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_us_description_3',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='About Us Description 3'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='governance_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Governance Text'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission_statement',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Mission Statement'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission_text_1',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Mission Text 1'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission_text_2',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Mission Text 2'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='testimonial_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Testimonial Text'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Vision Text'),
        ),
    ]
