# Generated by Django 4.2.7 on 2026-06-08 13:19

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_aboutpage_about_us_description_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the announcement (for internal identification)', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Upload a poster/image for the popup', null=True, upload_to='popup_announcements/')),
                ('image_url', models.URLField(blank=True, help_text='Or enter an external image URL if no local file is uploaded')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Custom rich text details shown inside the modal', verbose_name='Announcement Content')),
                ('link', models.URLField(blank=True, help_text='Optional custom link to redirect users (e.g., Admission page)')),
                ('link_text', models.CharField(default='Learn More', help_text='Action button label', max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Check to display this announcement popup on the homepage')),
                ('show_once_per_session', models.BooleanField(default=True, help_text='If checked, the popup will only display once per browser session. Otherwise, it will show on every homepage load.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Popup Announcement',
                'verbose_name_plural': 'Popup Announcements',
            },
        ),
    ]
