# Generated by Django 4.2.7 on 2026-06-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_popupannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreadcrumbSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_image', models.ImageField(blank=True, help_text='Upload the default breadcrumb banner image used across all pages.', null=True, upload_to='breadcrumbs/', verbose_name='Default Background Image')),
                ('default_image_url', models.URLField(blank=True, help_text='Use an external URL if you are not uploading a local image.', verbose_name='Default Image URL (External)')),
                ('is_active', models.BooleanField(default=True, help_text='When checked, custom breadcrumb images are applied across the site. Uncheck to revert all pages to the default theme background.', verbose_name='Enable Custom Breadcrumb Images')),
            ],
            options={
                'verbose_name': 'Breadcrumb Settings (Global Default)',
                'verbose_name_plural': 'Breadcrumb Settings (Global Default)',
            },
        ),
        migrations.CreateModel(
            name='PageBreadcrumb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('about', 'About Us'), ('committees', 'Committees'), ('committee_detail', 'Committee Detail'), ('policies', 'Policies'), ('recognition', 'Achievements & Recognition'), ('staff_teaching', 'Teaching Staff'), ('staff_nonteaching', 'Non-Teaching Staff'), ('notices', 'Notice Board'), ('contact', 'Contact Us'), ('nss', 'NSS'), ('iic', 'IIC'), ('ugc', 'UGC'), ('nep', 'NEP 2020'), ('sports', 'Sports'), ('co_po', 'CO PO'), ('happenings', 'Recent Happenings'), ('happening_detail', 'Happening Detail'), ('event_detail', 'Event Detail'), ('academics_programs', 'Programs Offered'), ('academics_calendar', 'Academic Calendar'), ('academics_dept_detail', 'Department Detail'), ('students_admission', 'Admission Procedure'), ('students_online_admission', 'Online Admission'), ('students_fee_structure', 'Fee Structure'), ('students_scholarship', 'Scholarship'), ('students_library', 'Library'), ('students_alumni', 'Alumni'), ('students_merit_list', 'Merit List'), ('naac_home', 'NAAC'), ('naac_iqac', 'IQAC'), ('naac_iiqa', 'IIQA'), ('naac_ssr', 'SSR'), ('naac_dvv', 'DVV'), ('naac_atr', 'ATR'), ('gallery_images', 'Image Gallery'), ('gallery_videos', 'Video Gallery'), ('gallery_news', 'News Gallery'), ('feedback_student', 'Student Feedback'), ('feedback_parent', 'Parent Feedback'), ('feedback_faculty', 'Faculty Feedback'), ('feedback_alumni', 'Alumni Feedback'), ('grievances_anti_ragging', 'Anti Ragging Committee'), ('grievances_icc', 'Internal Complaints Committee (ICC)'), ('grievances_redressal', 'Grievance Redressal'), ('grievances_submit', 'Submit a Grievance'), ('custom_page', 'Custom Page')], help_text='Select the page this breadcrumb image applies to.', max_length=60, unique=True, verbose_name='Page')),
                ('custom_image', models.ImageField(blank=True, help_text='Upload a custom breadcrumb banner image for this specific page.', null=True, upload_to='breadcrumbs/pages/', verbose_name='Custom Background Image')),
                ('custom_image_url', models.URLField(blank=True, help_text='Use an external URL for the image if not uploading locally.', verbose_name='Custom Image URL (External)')),
                ('use_default', models.BooleanField(default=False, help_text='Check this to ignore the custom image above and use the site-wide default breadcrumb image instead.', verbose_name='Use Global Default Image')),
                ('is_active', models.BooleanField(default=True, help_text='When checked, this page-level override is applied. Uncheck to disable and fall back to the global default.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Page Breadcrumb Override',
                'verbose_name_plural': 'Page Breadcrumb Overrides',
                'ordering': ['page_key'],
            },
        ),
    ]
