# Generated by Django 4.2.7 on 2026-06-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_breadcrumb_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='breadcrumb_image_url',
            field=models.URLField(blank=True, help_text='Use an external URL if not uploading a local image. Leave blank to use theme default.', verbose_name='Breadcrumb Image URL (External)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='breadcrumb_image',
            field=models.ImageField(blank=True, help_text='Upload a custom breadcrumb banner image for the About page.', null=True, upload_to='breadcrumbs/about/', verbose_name='Breadcrumb Background Image'),
        ),
    ]
