# Generated by Django 4.2.7 on 2026-06-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_aboutpage_breadcrumb_imagefield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popupannouncement',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Popup Announcement', 'verbose_name_plural': 'Popup Announcements'},
        ),
        migrations.AddField(
            model_name='popupannouncement',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order in the popup list (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='breadcrumbsettings',
            name='is_active',
            field=models.BooleanField(default=True, help_text='When checked, per-page breadcrumb overrides can replace the global default. When unchecked, all pages use only the global default image above.', verbose_name='Enable Per-Page Overrides'),
        ),
        migrations.AlterField(
            model_name='popupannouncement',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Check to display this announcement in the popup list on the homepage'),
        ),
    ]
