# Generated by Django 4.2.7 on 2026-06-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_popupannouncement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSSActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(help_text='e.g. 01, 02', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('fa_icon', models.CharField(default='fa-star', help_text="FontAwesome icon class name, e.g. 'fa-user-md', 'fa-tooth', 'fa-tree'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'NSS Activity',
                'verbose_name_plural': 'NSS Activities',
                'ordering': ['order', 'serial_number'],
            },
        ),
        migrations.CreateModel(
            name='NSSGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='nss/gallery/')),
                ('image_url', models.URLField(blank=True, help_text='External URL for image if not uploaded locally')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'NSS Gallery Image',
                'verbose_name_plural': 'NSS Gallery Images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NSSPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(default='National Service Scheme Chaitanya Science and Arts College, Pamgarh', max_length=200)),
                ('banner_description', models.TextField(default="The NSS symbol is based on the 'Rath Wheel' of the Konark Sun Temple of Orissa. The giant wheel portrays the cycles of creation, preservation and release and signifies the movement in life across time and space. The design of the symbol, a simplified form of Sun Chariot Wheel primarily depicts movement. The wheel signifies the progressive cycle of life. It also stands for dynamism and progressive outlook of youth.")),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='nss/')),
                ('banner_image_url', models.URLField(blank=True, help_text='External URL for banner image if not uploaded locally')),
                ('banner_icon', models.FileField(blank=True, help_text='SVG/PNG icon for banner', null=True, upload_to='nss/icons/')),
                ('banner_icon_url', models.URLField(blank=True, help_text='External URL for banner icon if not uploaded locally')),
                ('about_title', models.CharField(default='Our NSS Activities', max_length=200)),
                ('about_description', models.TextField(default='The NSS Unit consists of 100 student volunteers. The Program Officer is expected to motivate the student youth to understand the values and philosophy of NSS. The overall functions of Program Officer are to help the students to plan, implement and evaluate the activities of NSS under his/her charge and give proper guidance and directions to the student volunteers.')),
            ],
            options={
                'verbose_name': 'NSS Page Settings',
                'verbose_name_plural': 'NSS Page Settings',
            },
        ),
        migrations.AddField(
            model_name='happening',
            name='is_nss_activity',
            field=models.BooleanField(default=False, help_text='Check if this event/happening is part of NSS activities and should appear in the NSS page slider', verbose_name='Is NSS Activity'),
        ),
    ]
