# Generated by Django 4.2.7 on 2026-06-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_nssactivity_nssgalleryimage_nsspagesettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IICGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='iic/gallery/')),
                ('image_url', models.URLField(blank=True, help_text='External URL for image if not uploaded locally')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'IIC Gallery Image',
                'verbose_name_plural': 'IIC Gallery Images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IICPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="INSTITUTION'S INNOVATION COUNCIL (IIC)", max_length=200)),
                ('sub_title', models.CharField(default='Ministry of Education Supported', max_length=200)),
                ('description', models.TextField(default='In the year 2018, the Ministry of Education (MoE) through MoE’s Innovation Cell (MIC) launched the Institution’s Innovation Council (IIC) program in collaboration with AICTE for Higher Educational Institutions (HEIs) to systematically foster the culture of innovation and start-up ecosystem in education institutions. Primarily, IIC’s role is to engage large number of faculty, students and staff in various innovation and entrepreneurship related activities such as ideation, Problem solving, Proof of Concept development, Design Thinking, IPR, project handling and management at Pre-incubation/Incubation stage, etc., so that innovation and entrepreneurship ecosystem gets established and stabilized in HEIs.')),
                ('about_image_1', models.ImageField(blank=True, null=True, upload_to='iic/')),
                ('about_image_1_url', models.CharField(blank=True, max_length=300)),
                ('about_image_2', models.ImageField(blank=True, null=True, upload_to='iic/')),
                ('about_image_2_url', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'IIC Page Settings',
                'verbose_name_plural': 'IIC Page Settings',
            },
        ),
        migrations.AddField(
            model_name='happening',
            name='is_iic_activity',
            field=models.BooleanField(default=False, help_text='Check if this event/happening is part of IIC activities and should appear in the IIC page slider', verbose_name='Is IIC Activity'),
        ),
    ]
