# Generated by Django 4.2.7 on 2026-06-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_iicgalleryimage_iicpagesettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='video', max_length=10)),
                ('title', models.CharField(help_text='e.g. Cleaner, Greener & Sustainable', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Upload cover image / photo', null=True, upload_to='campus_media/')),
                ('image_url', models.URLField(blank=True, help_text='External cover image URL if not uploading locally')),
                ('video_url', models.URLField(blank=True, help_text='YouTube video URL (for Video type)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campus Media / Video',
                'verbose_name_plural': 'Campus Media & Videos',
                'ordering': ['order', 'id'],
            },
        ),
    ]
