# Generated by Django 4.2.7 on 2026-06-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_campusmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Laboratories, Library, Seminar Hall', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated slug (leave blank to auto-generate)', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the infrastructure')),
                ('video_url', models.URLField(blank=True, help_text='Optional YouTube video URL for a tour/showcase of this infrastructure')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which it will be displayed')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Infrastructure Section',
                'verbose_name_plural': 'Infrastructure Sections',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InfrastructureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload local image', null=True, upload_to='infrastructure/')),
                ('image_url', models.URLField(blank=True, help_text='Or enter external image URL')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.infrastructure')),
            ],
            options={
                'verbose_name': 'Infrastructure Image',
                'verbose_name_plural': 'Infrastructure Images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
