# Generated by Django 4.2.7 on 2026-06-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_productcategory_product_slug_productreview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sports/gallery/')),
                ('image_url', models.URLField(blank=True, help_text='External URL for image if not uploaded locally', max_length=500)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sport_tag', models.CharField(blank=True, help_text='e.g. Cricket, Volleyball, Athletics', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sports Gallery Image',
                'verbose_name_plural': 'Sports Gallery Images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SportsPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_intro_title', models.CharField(default='Sports & Athletics at CSAC', max_length=200)),
                ('page_intro', models.TextField(default='Chaitanya Science and Arts College believes in the all-round development of its students. Physical education and sports form an integral part of our curriculum. The college boasts excellent sports infrastructure, training programs and coaches that encourage students to participate at regional, state, and national levels.', help_text='Introduction paragraph shown at the top of the Sports page.')),
                ('facilities', models.TextField(default='Outdoor Sports Ground (Cricket, Football, Athletics)\nIndoor Games Arena (Table Tennis, Chess, Carrom, Badminton)\nFitness Center & Gymnasium\nVolleyball & Basketball Courts\nSports Library & Media Room', help_text='List of sports facilities, one per line. Displayed as a bullet list.')),
                ('achievements', models.TextField(default='Annual Athletic Meet — Inter-departmental athletics challenges\nChaitanya Trophy — Inter-collegiate Cricket & Volleyball tournament\nYoga Day Celebrations — Campus-wide training on International Yoga Day', help_text='Sports achievements/events, one per line.')),
                ('policies', models.TextField(default='Sports quota admissions for outstanding regional/national players\nCash incentives and fee concessions for tournament winners\nSpecial academic support and attendance relief during tournaments', help_text='Sports policies/benefits, one per line.')),
                ('show_notices', models.BooleanField(default=True, verbose_name='Show Sports Notices Section')),
                ('show_events', models.BooleanField(default=True, verbose_name='Show Upcoming Sports Events Section')),
                ('show_gallery', models.BooleanField(default=True, verbose_name='Show Sports Gallery Section')),
                ('show_happenings', models.BooleanField(default=True, verbose_name='Show Sports Happenings Section')),
            ],
            options={
                'verbose_name': 'Sports Page Settings',
                'verbose_name_plural': 'Sports Page Settings',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='is_sports_event',
            field=models.BooleanField(default=False, help_text='Check to show this event in the Sports page Upcoming Events section', verbose_name='Is Sports Event'),
        ),
        migrations.AddField(
            model_name='happening',
            name='is_sports_activity',
            field=models.BooleanField(default=False, help_text='Check if this event/happening is a sports activity and should appear in the Sports page', verbose_name='Is Sports Activity'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('latest', 'Latest'), ('exam', 'Exam'), ('admission', 'Admission'), ('students', 'Students'), ('sports', 'Sports')], default='latest', max_length=20),
        ),
    ]
