# Generated by Django 4.2.7 on 2026-06-09 19:37

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_sports_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='NEPTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. NEP Syllabus, General Guidelines', max_length=200, verbose_name='Tab Title')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='The main rich text content displayed inside this tab.', verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, help_text='For ordering tabs on the page.')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NEP Tab',
                'verbose_name_plural': 'NEP Tabs',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='NEPTabLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='Web Link / URL')),
                ('title', models.CharField(help_text='e.g. Official ABC Portal, Digilocker Website', max_length=250, verbose_name='Link Label/Text')),
                ('order', models.PositiveIntegerField(default=0)),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.neptab', verbose_name='NEP Tab')),
            ],
            options={
                'verbose_name': 'NEP Tab Link',
                'verbose_name_plural': 'NEP Tab Links',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NEPTabFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='nep/files/', verbose_name='Upload File')),
                ('title', models.CharField(help_text='e.g. NEP Syllabus PDF, Academic Credit Rules', max_length=250, verbose_name='File Title/Label')),
                ('order', models.PositiveIntegerField(default=0)),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.neptab', verbose_name='NEP Tab')),
            ],
            options={
                'verbose_name': 'NEP Tab File',
                'verbose_name_plural': 'NEP Tab Files',
                'ordering': ['order', 'id'],
            },
        ),
    ]
