# Generated by Django 4.2.7 on 2026-06-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_nep_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, verbose_name='Category')),
                ('num_books', models.PositiveIntegerField(verbose_name='No. of Books')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Library Book Category',
                'verbose_name_plural': 'Library Book Categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LibraryBookSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200, verbose_name='Book Title')),
                ('author', models.CharField(max_length=200, verbose_name='Author')),
                ('recommended_by', models.CharField(max_length=150, verbose_name='Recommended By')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('reason', models.TextField(blank=True, verbose_name='Reason for Suggestion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Library Book Suggestion',
                'verbose_name_plural': 'Library Book Suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LibraryPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_intro_title', models.CharField(default='Learning Resources of the College: Smt. Urmila Devi Smriti Pustkaalaya', max_length=200)),
                ('page_intro', models.TextField(default='Discover the heart of academic exploration at the College Library, established in 2001 in loving memory of Smt. Urmila Devi. More than just a repository of knowledge, our library is a dynamic hub that caters to the diverse needs of both faculty and students.')),
                ('about_library_title', models.CharField(default='About The Library', max_length=200)),
                ('about_library_text', models.TextField(default='With a spacious environment welcoming up to 100 readers, we offer semi-automated services and house an impressive collection of 2000 physical books and research journals. Access to digital subscriptions such as INFIBNET and open-access journals enriches research opportunities. With RFID technology ensuring seamless operations, our library hosts a variety of engaging activities, including orientation programs, faculty development seminars, and participatory reading club activities. Guided by our dedicated Library Committee, we are committed to fostering a culture of learning and intellectual exploration. Welcome to your gateway to knowledge and inspiration.')),
                ('future_plan_title', models.CharField(default='Future Plan', max_length=200)),
                ('future_plan_text', models.TextField(default='The future plan for the library involves expanding its physical space and digital infrastructure to accommodate growth and enhance accessibility. This includes fully automating processes like book checkouts and inventory management, while also prioritizing the digitization of collections and integration of digital resources. Collaborative partnerships, user training, and ongoing evaluation will ensure that the library remains a cutting-edge hub for research and learning in the digital age.')),
                ('library_image', models.ImageField(blank=True, null=True, upload_to='library/')),
                ('library_image_url', models.CharField(blank=True, default='/static/assets/images/feature/0001.png', max_length=500)),
                ('sections_text', models.TextField(default='Reference Section\nCirculation Section\nPeriodical Section', help_text='Enter one section per line.')),
                ('about_services_text', models.TextField(default='The library has automated all its library activities to provide effective and wide range of academic resources such as books, journals, online databases.')),
                ('new_suggestion_text', models.TextField(default='The library always encourages all students and faculty to recommend new books in order to strengthen their collection.')),
            ],
            options={
                'verbose_name': 'Library Page Settings',
                'verbose_name_plural': 'Library Page Settings',
            },
        ),
        migrations.CreateModel(
            name='LibraryResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('website_url', models.URLField(max_length=500, verbose_name='Website')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Library Resource',
                'verbose_name_plural': 'Library Resources',
                'ordering': ['order', 'id'],
            },
        ),
    ]
