# Generated by Django 4.2.7 on 2026-06-09 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_librarybookcategory_librarybooksuggestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload local image', null=True, upload_to='library/gallery/')),
                ('image_url', models.URLField(blank=True, help_text='Or enter external image URL', max_length=500)),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.librarypagesettings', verbose_name='Library Settings')),
            ],
            options={
                'verbose_name': 'Library Gallery Image',
                'verbose_name_plural': 'Library Gallery Images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
