# Generated by Django 4.2.7 on 2026-06-10 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_librarygalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display name for the menu item', max_length=100)),
                ('url', models.CharField(help_text='URL path (e.g. /about/) or named Django URL pattern (e.g. core:about) or external link (e.g. https://...)', max_length=255)),
                ('is_named_url', models.BooleanField(default=False, help_text="Check if the URL is a Django URL name pattern (e.g. 'core:about')", verbose_name='Is Named URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers come first)')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle visibility on the navbar')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='Open in new tab')),
                ('parent', models.ForeignKey(blank=True, help_text='Select parent menu item. Leave blank to make it a top-level menu.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
