# Generated by Django 4.2.7 on 2026-06-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address_line1_font_color',
            field=models.CharField(default='#000000', max_length=20, verbose_name='Address Line 1 Font Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_line1_font_family',
            field=models.CharField(default='Roboto Slab', max_length=100, verbose_name='Address Line 1 Font Family'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_line1_font_size',
            field=models.CharField(default='20px', max_length=50, verbose_name='Address Line 1 Font Size'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_line1_google_font_url',
            field=models.URLField(blank=True, help_text='Google Fonts stylesheet URL', verbose_name='Address Line 1 Google Font Link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_line2_font_color',
            field=models.CharField(default='#000000', max_length=20, verbose_name='Address Line 2 Font Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_line2_font_family',
            field=models.CharField(default='Roboto Slab', max_length=100, verbose_name='Address Line 2 Font Family'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_line2_font_size',
            field=models.CharField(default='16px', max_length=50, verbose_name='Address Line 2 Font Size'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_line2_google_font_url',
            field=models.URLField(blank=True, help_text='Google Fonts stylesheet URL', verbose_name='Address Line 2 Google Font Link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='college_name_en_font_color',
            field=models.CharField(default='#E61013', max_length=20, verbose_name='College Name (EN) Font Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='college_name_en_font_family',
            field=models.CharField(default='Roboto Slab', max_length=100, verbose_name='College Name (EN) Font Family'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='college_name_en_font_size',
            field=models.CharField(default='24px', max_length=50, verbose_name='College Name (EN) Font Size'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='college_name_en_google_font_url',
            field=models.URLField(blank=True, help_text='Google Fonts stylesheet URL', verbose_name='College Name (EN) Google Font Link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='college_name_hi_font_color',
            field=models.CharField(default='#E61013', max_length=20, verbose_name='College Name (HI) Font Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='college_name_hi_font_family',
            field=models.CharField(default='Roboto Slab', max_length=100, verbose_name='College Name (HI) Font Family'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='college_name_hi_font_size',
            field=models.CharField(default='24px', max_length=50, verbose_name='College Name (HI) Font Size'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='college_name_hi_google_font_url',
            field=models.URLField(blank=True, help_text='Google Fonts stylesheet URL', verbose_name='College Name (HI) Google Font Link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_font_color',
            field=models.CharField(default='#E61013', max_length=20, verbose_name='Tagline Font Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_font_family',
            field=models.CharField(default='Roboto Slab', max_length=100, verbose_name='Tagline Font Family'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_font_size',
            field=models.CharField(default='16px', max_length=50, verbose_name='Tagline Font Size'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_google_font_url',
            field=models.URLField(blank=True, help_text='Google Fonts stylesheet URL', verbose_name='Tagline Google Font Link'),
        ),
    ]
