# Generated by Django 4.2.7 on 2026-06-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_sitesettings_address_line1_font_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Visitor Count',
                'verbose_name_plural': 'Visitor Count',
            },
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_us_image',
            field=models.ImageField(blank=True, help_text='Upload a local image file to display in the main About Us section.', null=True, upload_to='about/', verbose_name='About Us Main Image'),
        ),
    ]
