# Generated by Django 4.2.7 on 2026-06-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_uploadeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='header_image',
            field=models.ImageField(blank=True, help_text="Upload a custom header image banner. This will replace the text header and logos if 'Use Image Header' is checked.", null=True, upload_to='headers/', verbose_name='Header Image (Banner)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='use_image_header',
            field=models.BooleanField(default=False, help_text='Check this to display the custom header image banner instead of the default text and logos.', verbose_name='Use Image Header'),
        ),
    ]
