# Generated by Django 6.0.6 on 2026-06-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_sitesettings_header_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagebreadcrumb',
            name='page_key',
            field=models.CharField(choices=[('about', 'About Us'), ('committees', 'Committees'), ('committee_detail', 'Committee Detail'), ('policies', 'Policies'), ('recognition', 'Achievements & Recognition'), ('staff_teaching', 'Teaching Staff'), ('staff_nonteaching', 'Non-Teaching Staff'), ('notices', 'Notice Board'), ('contact', 'Contact Us'), ('nss', 'NSS'), ('iic', 'IIC'), ('ugc', 'UGC'), ('nep', 'NEP 2020'), ('sports', 'Sports'), ('co_po', 'CO PO'), ('happenings', 'Recent Happenings'), ('happening_detail', 'Happening Detail'), ('event_detail', 'Event Detail'), ('academics_programs', 'Programs Offered'), ('academics_calendar', 'Academic Calendar'), ('academics_dept_detail', 'Department Detail'), ('students_admission', 'Admission Procedure'), ('students_online_admission', 'Online Admission'), ('students_fee_structure', 'Fee Structure'), ('students_scholarship', 'Scholarship'), ('students_library', 'Library'), ('students_alumni', 'Alumni'), ('students_merit_list', 'Merit List'), ('students_syllabus', 'Syllabus'), ('naac_home', 'NAAC'), ('naac_iqac', 'IQAC'), ('naac_iiqa', 'IIQA'), ('naac_ssr', 'SSR'), ('naac_dvv', 'DVV'), ('naac_atr', 'ATR'), ('gallery_images', 'Image Gallery'), ('gallery_videos', 'Video Gallery'), ('gallery_news', 'News Gallery'), ('feedback_student', 'Student Feedback'), ('feedback_parent', 'Parent Feedback'), ('feedback_faculty', 'Faculty Feedback'), ('feedback_alumni', 'Alumni Feedback'), ('grievances_anti_ragging', 'Anti Ragging Committee'), ('grievances_icc', 'Internal Complaints Committee (ICC)'), ('grievances_redressal', 'Grievance Redressal'), ('grievances_submit', 'Submit a Grievance'), ('custom_page', 'Custom Page'), ('infrastructure', 'Infrastructure')], help_text='Select the page this breadcrumb image applies to.', max_length=60, unique=True, verbose_name='Page'),
        ),
    ]
