# Generated by Django 6.0.6 on 2026-06-18 09:47

from django.db import migrations


def migrate_marquee_notices(apps, schema_editor):
    MarqueeNotice = apps.get_model('core', 'MarqueeNotice')
    Notice = apps.get_model('core', 'Notice')
    from django.utils import timezone
    for mn in MarqueeNotice.objects.all():
        if not Notice.objects.filter(title=mn.text, document_url=mn.link).exists():
            Notice.objects.create(
                title=mn.text,
                category='latest',
                document_url=mn.link,
                published_date=mn.created_at.date() if mn.created_at else timezone.now().date(),
                show_in_marquee=mn.is_active,
                is_active=mn.is_active,
            )


def rollback_marquee_notices(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_pagebreadcrumb_page_key'),
    ]

    operations = [
        migrations.RunPython(migrate_marquee_notices, rollback_marquee_notices),
    ]
