# Generated by Django 6.0.6 on 2026-06-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20260618_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarqueeNotice',
        ),
    ]
