# Generated by Django 6.0.6 on 2026-06-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_delete_marqueenotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructureimage',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for this subcategory or image section on the detail page'),
        ),
        migrations.AlterField(
            model_name='infrastructureimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Subcategory or facility name shown on the detail page', max_length=250),
        ),
    ]
