# Generated by Django 6.0.6 on 2026-07-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_facilities_menu_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address shown on the home and about pages', max_length=254),
        ),
    ]
