# Generated by Django 6.0.6 on 2026-07-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_leadership_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingStaffPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Faculty List 2025-26', help_text='Main heading shown on the teaching staff page', max_length=200)),
                ('subtitle', models.TextField(default='Meet our dedicated, qualified, and experienced teaching staff members.', help_text='Short description shown below the heading')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teaching Staff Page Settings',
                'verbose_name_plural': 'Teaching Staff Page Settings',
            },
        ),
    ]
