# Generated by Django 6.0.6 on 2026-07-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_teaching_staff_page_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonTeachingStaffPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Non-Teaching Staff', help_text='Main heading shown on the non-teaching staff page', max_length=200)),
                ('subtitle', models.TextField(default='Meet our dedicated administrative and support staff members.', help_text='Short description shown below the heading')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Non-Teaching Staff Page Settings',
                'verbose_name_plural': 'Non-Teaching Staff Page Settings',
            },
        ),
    ]
