# Generated by Django 6.0.6 on 2026-07-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_nonteaching_staff_page_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonTeachingStaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=200)),
                ('department_section', models.CharField(help_text='e.g. Administration, Accounts, Library', max_length=200, verbose_name='Department / Section')),
                ('qualification', models.CharField(blank=True, max_length=300)),
                ('contact', models.CharField(blank=True, help_text='Phone number or email', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Non-Teaching Staff Member',
                'verbose_name_plural': 'Non-Teaching Staff Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
