# Generated by Django 5.2.14 on 2026-06-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IQACMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('chairman', 'Chairman'), ('coordinator', 'Coordinator'), ('member', 'Member'), ('external', 'External Member')], default='member', max_length=20)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'IQAC Member',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NAACCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_number', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, upload_to='naac/criteria/')),
                ('document_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'NAAC Criteria',
                'verbose_name_plural': 'NAAC Criteria',
                'ordering': ['order', 'criterion_number'],
            },
        ),
        migrations.CreateModel(
            name='NAACDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('iiqa', 'IIQA'), ('ssr', 'SSR'), ('dvv', 'DVV'), ('atr', 'ATR'), ('naac', 'NAAC General'), ('aqar', 'AQAR')], max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('document', models.FileField(blank=True, upload_to='naac/documents/')),
                ('document_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'NAAC Document',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NAACInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default='A', max_length=5)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('accreditation_date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('certificate_image', models.ImageField(blank=True, upload_to='naac/')),
            ],
            options={
                'verbose_name': 'NAAC Info',
                'verbose_name_plural': 'NAAC Info',
            },
        ),
    ]
