# Generated by Django 4.2.7 on 2026-06-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naac', '0002_alter_naaccriteria_criterion_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='naaccriteria',
            name='criterion',
            field=models.CharField(choices=[('1', 'Criterion I'), ('2', 'Criterion II'), ('3', 'Criterion III'), ('4', 'Criterion IV'), ('5', 'Criterion V'), ('6', 'Criterion VI'), ('7', 'Criterion VII')], default='1', max_length=2, verbose_name='Criterion'),
        ),
        migrations.AlterField(
            model_name='naaccriteria',
            name='criterion_number',
            field=models.CharField(max_length=10, verbose_name='Metric Number'),
        ),
    ]
