# Generated by Django 5.2.14 on 2026-06-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.CharField(choices=[('anti_ragging', 'Anti-Ragging Committee'), ('icc', 'Internal Complaints Committee (ICC)'), ('redressal', 'Grievance Redressal Committee')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('objectives', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, upload_to='grievances/docs/')),
            ],
            options={
                'verbose_name': 'Committee Info',
                'verbose_name_plural': 'Committees Info',
            },
        ),
        migrations.CreateModel(
            name='GrievanceCommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.CharField(choices=[('anti_ragging', 'Anti-Ragging Committee'), ('icc', 'Internal Complaints Committee (ICC)'), ('redressal', 'Grievance Redressal Committee')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=200)),
                ('role_in_committee', models.CharField(blank=True, help_text='e.g. Chairman, Member, Convenor', max_length=100)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Committee Member',
                'ordering': ['committee', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GrievanceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grievance_type', models.CharField(choices=[('anti_ragging', 'Anti-Ragging'), ('icc', 'Internal Complaints (ICC)'), ('redressal', 'General Grievance')], max_length=20)),
                ('complainant_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('roll_number', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('supporting_document', models.FileField(blank=True, upload_to='grievances/docs/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, help_text='Admin remarks / resolution notes')),
            ],
            options={
                'verbose_name': 'Grievance Submission',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
