# Generated by Django 6.0.6 on 2026-07-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionFest2026Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Your Name')),
                ('visitor_type', models.CharField(choices=[('school_student', 'School Student'), ('college_student', 'College Student'), ('graduate', 'Graduate / Postgraduate'), ('parent', 'Parent / Guardian'), ('alumni', 'Alumni'), ('local_visitor', 'Local Visitor'), ('other', 'Other')], max_length=30, verbose_name='You are a')),
                ('institution_name', models.CharField(blank=True, max_length=250, verbose_name='School / College / Institution Name')),
                ('city_village', models.CharField(blank=True, max_length=150, verbose_name='City / Village')),
                ('attractions', models.TextField(help_text='Comma-separated selections', verbose_name='What attracted you to Admission Fest 2026?')),
                ('heard_from', models.CharField(choices=[('social_media', 'Instagram / Facebook / Social Media'), ('whatsapp', 'WhatsApp'), ('friends_family', 'Friends / Family'), ('school_college', 'School / College'), ('posters', 'Posters / Banners'), ('staff_students', 'College Staff / Students'), ('other', 'Other')], max_length=30, verbose_name='How did you hear about Admission Fest 2026?')),
                ('overall_rating', models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ Excellent'), (4, '⭐⭐⭐⭐ Very Good'), (3, '⭐⭐⭐ Good'), (2, '⭐⭐ Fair'), (1, '⭐ Poor')], verbose_name='Overall, how would you rate Admission Fest 2026?')),
                ('organization_rating', models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ Excellent'), (4, '⭐⭐⭐⭐ Very Good'), (3, '⭐⭐⭐ Good'), (2, '⭐⭐ Fair'), (1, '⭐ Poor')], verbose_name='How would you rate the organization of the event?')),
                ('hospitality_rating', models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ Excellent'), (4, '⭐⭐⭐⭐ Very Good'), (3, '⭐⭐⭐ Good'), (2, '⭐⭐ Fair'), (1, '⭐ Poor')], verbose_name='How would you rate the welcome and hospitality?')),
                ('atmosphere_rating', models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ Excellent'), (4, '⭐⭐⭐⭐ Very Good'), (3, '⭐⭐⭐ Good'), (2, '⭐⭐ Fair'), (1, '⭐ Poor')], verbose_name='How would you rate the event atmosphere?')),
                ('stage_programme_rating', models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ Excellent'), (4, '⭐⭐⭐⭐ Very Good'), (3, '⭐⭐⭐ Good'), (2, '⭐⭐ Fair'), (1, '⭐ Poor')], verbose_name='How would you rate the stage and programme arrangements?')),
                ('crowd_management_rating', models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ Excellent'), (4, '⭐⭐⭐⭐ Very Good'), (3, '⭐⭐⭐ Good'), (2, '⭐⭐ Fair'), (1, '⭐ Poor')], verbose_name='How satisfied were you with the crowd management?')),
                ('facilities_rating', models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ Excellent'), (4, '⭐⭐⭐⭐ Very Good'), (3, '⭐⭐⭐ Good'), (2, '⭐⭐ Fair'), (1, '⭐ Poor')], verbose_name='How would you rate the overall facilities provided during the event?')),
                ('attended_meet_greet', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('audience', 'I watched from the audience')], max_length=20, verbose_name='Did you attend the Mann Qureshi Meet & Greet?')),
                ('meet_greet_rating', models.IntegerField(blank=True, choices=[(5, '⭐⭐⭐⭐⭐ Excellent'), (4, '⭐⭐⭐⭐ Very Good'), (3, '⭐⭐⭐ Good'), (2, '⭐⭐ Fair'), (1, '⭐ Poor')], null=True, verbose_name='How would you rate your overall Mann Qureshi Meet & Greet experience?')),
                ('excitement_level', models.CharField(choices=[('extremely', 'Extremely Excited'), ('very', 'Very Excited'), ('excited', 'Excited'), ('somewhat', 'Somewhat Excited'), ('neutral', 'Neutral')], max_length=20, verbose_name='How excited were you to see Mann Qureshi at Admission Fest 2026?')),
                ('presence_made_exciting', models.CharField(choices=[('yes', 'Yes, definitely'), ('somewhat', 'Somewhat'), ('no', 'No')], max_length=20, verbose_name="Did Mann Qureshi's presence make Admission Fest 2026 more exciting?")),
                ('best_part', models.TextField(blank=True, verbose_name='What did you enjoy the most about Admission Fest 2026?')),
                ('improvements', models.TextField(blank=True, verbose_name='What could we improve for future events?')),
                ('would_recommend', models.CharField(choices=[('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No')], max_length=10, verbose_name='Would you recommend Admission Fest to friends and family?')),
                ('would_attend_again', models.CharField(choices=[('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No')], max_length=10, verbose_name='Would you like to attend similar events at our college again?')),
                ('interested_in_admission', models.CharField(blank=True, choices=[('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No')], max_length=10, verbose_name='Are you interested in taking admission at Chaitanya Science and Arts College?')),
                ('additional_comments', models.TextField(blank=True, verbose_name='Any additional comments or suggestions?')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admission Fest 2026 Feedback',
                'verbose_name_plural': 'Admission Fest 2026 Feedback',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
