# Generated by Django 6.0.6 on 2026-07-24 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_admission_fest_2026_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFeedbackCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Form heading, e.g. "Admission Fest 2026 – Feedback Form"', max_length=200)),
                ('slug', models.SlugField(help_text='URL path: /feedback/events/<slug>/', max_length=80, unique=True)),
                ('menu_title', models.CharField(blank=True, help_text='Short title for navbar (defaults to title)', max_length=120)),
                ('subtitle', models.CharField(blank=True, help_text='e.g. Special Meet & Greet with Mann Qureshi', max_length=300)),
                ('featured_guest', models.CharField(blank=True, help_text='Guest name used in Meet & Greet questions (e.g. Mann Qureshi)', max_length=150)),
                ('institution_line', models.CharField(default='Chaitanya Science and Arts College, Pamgarh', max_length=200)),
                ('accreditation_line', models.CharField(blank=True, default="An Autonomous Institution | NAAC Accredited Grade 'A'", max_length=200)),
                ('intro_text', models.TextField(help_text='Shown above the form. Use blank lines for paragraphs.')),
                ('confirmation_message', models.TextField(default='Thank You for Your Feedback!\n\nWe are delighted that you were a part of this event.\n\nYour feedback will help us organize even better events in the future.\n\nChaitanya Science and Arts College, Pamgarh\n✨ Learn • Grow • Achieve ✨')),
                ('tagline', models.CharField(blank=True, default='✨ Learn • Grow • Achieve ✨', max_length=100)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Public form is open for responses')),
                ('show_in_menu', models.BooleanField(default=True, help_text='List under Feedback in the navbar')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('show_meet_greet_section', models.BooleanField(default=True, verbose_name='Show Meet & Greet section')),
                ('show_college_experience_section', models.BooleanField(default=True, verbose_name='Show College Experience section')),
                ('show_event_impact_section', models.BooleanField(default=True, verbose_name='Show Event Impact section')),
                ('show_voice_section', models.BooleanField(default=True, verbose_name='Show Your Voice section')),
                ('visitor_type_options', models.TextField(default='School Student\nCollege Student\nGraduate / Postgraduate\nParent / Guardian\nAlumni\nLocal Visitor\nOther', help_text='One option per line')),
                ('attraction_options', models.TextField(default='Meet & Greet with celebrity / guest\nAdmission / Course Information\nCollege Campus Visit\nEntertainment & Activities\nFriends / Family\nSocial Media Promotion\nCollege Invitation\nOther', help_text='Checkbox options – one per line')),
                ('heard_from_options', models.TextField(default='Instagram / Facebook / Social Media\nWhatsApp\nFriends / Family\nSchool / College\nPosters / Banners\nCollege Staff / Students\nOther')),
                ('attended_meet_greet_options', models.TextField(default='Yes\nNo\nI watched from the audience')),
                ('excitement_options', models.TextField(default='Extremely Excited\nVery Excited\nExcited\nSomewhat Excited\nNeutral')),
                ('presence_made_exciting_options', models.TextField(default='Definitely Yes\nYes\nSomewhat\nNot Much\nNo')),
                ('enjoy_meet_greet_options', models.TextField(default='Seeing the guest in person\nMeeting / interacting with them\nTaking photos / selfies\nStage interaction\nOverall atmosphere\nBeing part of the crowd\nOther')),
                ('college_knowledge_options', models.TextField(default='Yes, a lot\nYes, somewhat\nA little\nNot really')),
                ('learned_options', models.TextField(default='Courses & Programmes\nCollege Facilities\nAdmission Process\nScholarships\nCampus Environment\nFaculty & Student Interaction\nCareer Opportunities\nCultural / Student Activities\nI mainly attended the event\nOther', help_text='Checkbox options – one per line')),
                ('campus_impression_options', models.TextField(default='Excellent\nVery Good\nGood\nAverage\nNeeds Improvement')),
                ('another_celebrity_options', models.TextField(default='Definitely Yes!\nYes\nMaybe\nNot Sure\nNo')),
                ('final_description_options', models.TextField(default='Amazing – Loved It!\nExcellent\nVery Good\nGood\nAverage\nNeeds Improvement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Feedback Form',
                'verbose_name_plural': 'Event Feedback Forms (create / edit)',
                'ordering': ['order', '-event_date', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='admissionfest2026feedback',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Admission Fest 2026 Feedback (legacy)', 'verbose_name_plural': 'Admission Fest 2026 Feedback (legacy)'},
        ),
        migrations.AlterField(
            model_name='admissionfest2026feedback',
            name='additional_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='admissionfest2026feedback',
            name='atmosphere_rating',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ Excellent'), (4, '⭐⭐⭐⭐ Very Good'), (3, '⭐⭐⭐ Good'), (2, '⭐⭐ Fair'), (1, '⭐ Poor')]),
        ),
        migrations.AlterField(
            model_name='admissionfest2026feedback',
            name='attended_meet_greet',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('audience', 'I watched from the audience')], max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionfest2026feedback',
            name='attractions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='admissionfest2026feedback',
            name='best_part',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='admissionfest2026feedback',
            name='city_village',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='admissionfest2026feedback',
            name='crowd_management_rating',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ Excellent'), (4, '⭐⭐⭐⭐ Very Good'), (3, '⭐⭐⭐ Good'), (2, '⭐⭐ Fair'), (1, '⭐ Poor')]),
        ),
        migrations.AlterField(
            model_name='admissionfest2026feedback',
            name='excitement_level',
            field=models.CharField(choices=[('extremely', 'Extremely Excited'), ('very', 'Very Excited'), ('excited', 'Excited'), ('somewhat', 'Somewhat Excited'), ('neutral', 'Neutral')], max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionfest2026feedback',
            name='facilities_rating',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ Excellent'), (4, '⭐⭐⭐⭐ Very Good'), (3, '⭐⭐⭐ Good'), (2, '⭐⭐ Fair'), (1, '⭐ Poor')]),
        ),
        migrations.AlterField(
            model_name='admissionfest2026feedback',
            name='heard_from',
            field=models.CharField(choices=[('social_media', 'Instagram / Facebook / Social Media'), ('whatsapp', 'WhatsApp'), ('friends_family', 'Friends / Family'), ('school_college', 'School / College'), ('posters', 'Posters / Banners'), ('staff_students', 'College Staff / Students'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='admissionfest2026feedback',
            name='hospitality_rating',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ Excellent'), (4, '⭐⭐⭐⭐ Very Good'), (3, '⭐⭐⭐ Good'), (2, '⭐⭐ Fair'), (1, '⭐ Poor')]),
        ),
        migrations.AlterField(
            model_name='admissionfest2026feedback',
            name='improvements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='admissionfest2026feedback',
            name='institution_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='admissionfest2026feedback',
            name='interested_in_admission',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='admissionfest2026feedback',
            name='meet_greet_rating',
            field=models.IntegerField(blank=True, choices=[(5, '⭐⭐⭐⭐⭐ Excellent'), (4, '⭐⭐⭐⭐ Very Good'), (3, '⭐⭐⭐ Good'), (2, '⭐⭐ Fair'), (1, '⭐ Poor')], null=True),
        ),
        migrations.AlterField(
            model_name='admissionfest2026feedback',
            name='organization_rating',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ Excellent'), (4, '⭐⭐⭐⭐ Very Good'), (3, '⭐⭐⭐ Good'), (2, '⭐⭐ Fair'), (1, '⭐ Poor')]),
        ),
        migrations.AlterField(
            model_name='admissionfest2026feedback',
            name='overall_rating',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ Excellent'), (4, '⭐⭐⭐⭐ Very Good'), (3, '⭐⭐⭐ Good'), (2, '⭐⭐ Fair'), (1, '⭐ Poor')]),
        ),
        migrations.AlterField(
            model_name='admissionfest2026feedback',
            name='presence_made_exciting',
            field=models.CharField(choices=[('yes', 'Yes, definitely'), ('somewhat', 'Somewhat'), ('no', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionfest2026feedback',
            name='stage_programme_rating',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ Excellent'), (4, '⭐⭐⭐⭐ Very Good'), (3, '⭐⭐⭐ Good'), (2, '⭐⭐ Fair'), (1, '⭐ Poor')]),
        ),
        migrations.AlterField(
            model_name='admissionfest2026feedback',
            name='visitor_type',
            field=models.CharField(choices=[('school_student', 'School Student'), ('college_student', 'College Student'), ('graduate', 'Graduate / Postgraduate'), ('parent', 'Parent / Guardian'), ('alumni', 'Alumni'), ('local_visitor', 'Local Visitor'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='admissionfest2026feedback',
            name='would_attend_again',
            field=models.CharField(choices=[('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='admissionfest2026feedback',
            name='would_recommend',
            field=models.CharField(choices=[('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No')], max_length=10),
        ),
        migrations.CreateModel(
            name='EventFeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Your Name')),
                ('visitor_type', models.CharField(max_length=100, verbose_name='You are a')),
                ('institution_name', models.CharField(blank=True, max_length=250, verbose_name='School / College / Institution Name')),
                ('city_village', models.CharField(blank=True, max_length=150, verbose_name='City / Village')),
                ('attractions', models.TextField(help_text='Comma-separated selections', verbose_name='What attracted you to this event?')),
                ('heard_from', models.CharField(max_length=150, verbose_name='How did you hear about this event?')),
                ('overall_rating', models.IntegerField(choices=[(5, '5 – Excellent'), (4, '4 – Very Good'), (3, '3 – Good'), (2, '2 – Fair'), (1, '1 – Poor')], verbose_name='Overall event rating')),
                ('organization_rating', models.IntegerField(choices=[(5, '5 – Excellent'), (4, '4 – Very Good'), (3, '3 – Good'), (2, '2 – Fair'), (1, '1 – Poor')], verbose_name='Organization')),
                ('hospitality_rating', models.IntegerField(choices=[(5, '5 – Excellent'), (4, '4 – Very Good'), (3, '3 – Good'), (2, '2 – Fair'), (1, '1 – Poor')], verbose_name='Welcome & hospitality')),
                ('atmosphere_rating', models.IntegerField(choices=[(5, '5 – Excellent'), (4, '4 – Very Good'), (3, '3 – Good'), (2, '2 – Fair'), (1, '1 – Poor')], verbose_name='Event atmosphere')),
                ('stage_programme_rating', models.IntegerField(choices=[(5, '5 – Excellent'), (4, '4 – Very Good'), (3, '3 – Good'), (2, '2 – Fair'), (1, '1 – Poor')], verbose_name='Stage & programme arrangements')),
                ('crowd_management_rating', models.IntegerField(choices=[(5, '5 – Excellent'), (4, '4 – Very Good'), (3, '3 – Good'), (2, '2 – Fair'), (1, '1 – Poor')], verbose_name='Crowd management')),
                ('facilities_rating', models.IntegerField(choices=[(5, '5 – Excellent'), (4, '4 – Very Good'), (3, '3 – Good'), (2, '2 – Fair'), (1, '1 – Poor')], verbose_name='Facilities')),
                ('attended_meet_greet', models.CharField(blank=True, max_length=100)),
                ('meet_greet_rating', models.IntegerField(blank=True, choices=[(5, '5 – Excellent'), (4, '4 – Very Good'), (3, '3 – Good'), (2, '2 – Fair'), (1, '1 – Poor')], null=True)),
                ('excitement_level', models.CharField(blank=True, max_length=100)),
                ('presence_made_exciting', models.CharField(blank=True, max_length=100)),
                ('enjoy_most_meet_greet', models.CharField(blank=True, max_length=150)),
                ('college_knowledge', models.CharField(blank=True, max_length=100)),
                ('learned_experienced', models.TextField(blank=True, help_text='Comma-separated selections')),
                ('campus_impression', models.CharField(blank=True, max_length=100)),
                ('memorable_scale', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('attend_future_scale', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('recommend_events_scale', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('another_celebrity_meet', models.CharField(blank=True, max_length=100)),
                ('best_part', models.TextField(blank=True)),
                ('improvements', models.TextField(blank=True)),
                ('message_for_guest', models.TextField(blank=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('final_description', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='feedback.eventfeedbackcampaign')),
            ],
            options={
                'verbose_name': 'Event Feedback Response',
                'verbose_name_plural': 'Event Feedback Responses',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
