# Generated by Django 6.0.6 on 2026-07-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_event_feedback_campaigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfeedbackcampaign',
            name='accreditation_line_hi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Accreditation line (Hindi)'),
        ),
        migrations.AddField(
            model_name='eventfeedbackcampaign',
            name='another_celebrity_options_hi',
            field=models.TextField(blank=True, verbose_name='Another celebrity Meet & Greet options (Hindi)'),
        ),
        migrations.AddField(
            model_name='eventfeedbackcampaign',
            name='attended_meet_greet_options_hi',
            field=models.TextField(blank=True, verbose_name='Attended Meet & Greet options (Hindi)'),
        ),
        migrations.AddField(
            model_name='eventfeedbackcampaign',
            name='attraction_options_hi',
            field=models.TextField(blank=True, help_text='One Hindi label per line, same order as English list', verbose_name='Attraction options (Hindi)'),
        ),
        migrations.AddField(
            model_name='eventfeedbackcampaign',
            name='campus_impression_options_hi',
            field=models.TextField(blank=True, verbose_name='Campus impression options (Hindi)'),
        ),
        migrations.AddField(
            model_name='eventfeedbackcampaign',
            name='college_knowledge_options_hi',
            field=models.TextField(blank=True, verbose_name='College knowledge options (Hindi)'),
        ),
        migrations.AddField(
            model_name='eventfeedbackcampaign',
            name='confirmation_message_hi',
            field=models.TextField(blank=True, verbose_name='Confirmation message (Hindi)'),
        ),
        migrations.AddField(
            model_name='eventfeedbackcampaign',
            name='enjoy_meet_greet_options_hi',
            field=models.TextField(blank=True, verbose_name='Enjoy Meet & Greet options (Hindi)'),
        ),
        migrations.AddField(
            model_name='eventfeedbackcampaign',
            name='event_name_hi',
            field=models.CharField(blank=True, help_text='Used inside questions, e.g. एडमिशन फेस्ट 2026', max_length=200, verbose_name='Short event name (Hindi)'),
        ),
        migrations.AddField(
            model_name='eventfeedbackcampaign',
            name='excitement_options_hi',
            field=models.TextField(blank=True, verbose_name='Excitement options (Hindi)'),
        ),
        migrations.AddField(
            model_name='eventfeedbackcampaign',
            name='featured_guest_hi',
            field=models.CharField(blank=True, help_text='e.g. मान कुरैशी', max_length=150, verbose_name='Featured guest (Hindi)'),
        ),
        migrations.AddField(
            model_name='eventfeedbackcampaign',
            name='final_description_options_hi',
            field=models.TextField(blank=True, verbose_name='Final description options (Hindi)'),
        ),
        migrations.AddField(
            model_name='eventfeedbackcampaign',
            name='heard_from_options_hi',
            field=models.TextField(blank=True, help_text='One Hindi label per line, same order as English list', verbose_name='Heard from options (Hindi)'),
        ),
        migrations.AddField(
            model_name='eventfeedbackcampaign',
            name='institution_line_hi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Institution line (Hindi)'),
        ),
        migrations.AddField(
            model_name='eventfeedbackcampaign',
            name='intro_text_hi',
            field=models.TextField(blank=True, verbose_name='Intro text (Hindi)'),
        ),
        migrations.AddField(
            model_name='eventfeedbackcampaign',
            name='learned_options_hi',
            field=models.TextField(blank=True, verbose_name='Learned / experienced options (Hindi)'),
        ),
        migrations.AddField(
            model_name='eventfeedbackcampaign',
            name='menu_title_hi',
            field=models.CharField(blank=True, max_length=120, verbose_name='Menu title (Hindi)'),
        ),
        migrations.AddField(
            model_name='eventfeedbackcampaign',
            name='presence_made_exciting_options_hi',
            field=models.TextField(blank=True, verbose_name='Presence made exciting options (Hindi)'),
        ),
        migrations.AddField(
            model_name='eventfeedbackcampaign',
            name='subtitle_hi',
            field=models.CharField(blank=True, max_length=300, verbose_name='Subtitle (Hindi)'),
        ),
        migrations.AddField(
            model_name='eventfeedbackcampaign',
            name='tagline_hi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tagline (Hindi)'),
        ),
        migrations.AddField(
            model_name='eventfeedbackcampaign',
            name='title_hi',
            field=models.CharField(blank=True, help_text='हिन्दी शीर्षक – shown when language is Hindi', max_length=200, verbose_name='Title (Hindi)'),
        ),
        migrations.AddField(
            model_name='eventfeedbackcampaign',
            name='visitor_type_options_hi',
            field=models.TextField(blank=True, help_text='One Hindi label per line, same order as English list', verbose_name='Visitor type options (Hindi)'),
        ),
    ]
