# Generated by Django 6.0.6 on 2026-07-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_campaign_hindi_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfeedbackcampaign',
            name='contribution_areas_options',
            field=models.TextField(default='Financial assistance for needy students\nSubject expert / mentor\nSupport for library enrichment\nOther suggestions for development', help_text='Checkbox options – one per line. Contribution areas for college development.', verbose_name='Contribution area options (English)'),
        ),
        migrations.AddField(
            model_name='eventfeedbackcampaign',
            name='contribution_areas_options_hi',
            field=models.TextField(blank=True, default='निर्धन छात्रों हेतु आर्थिक सहायता\nविषय विशेषज्ञ / मार्गदर्शक\nपुस्तकालय संवर्धन हेतु सहयोग\nविकास हेतु अन्य कोई सुझाव', help_text='One Hindi label per line, same order as English list. e.g. निर्धन छात्रों हेतु आर्थिक सहायता', verbose_name='Contribution area options (Hindi)'),
        ),
        migrations.AddField(
            model_name='eventfeedbackresponse',
            name='contribution_areas',
            field=models.TextField(blank=True, help_text='Comma-separated selections', verbose_name='Areas of contribution to college development'),
        ),
        migrations.AddField(
            model_name='eventfeedbackresponse',
            name='contribution_other_suggestion',
            field=models.TextField(blank=True, verbose_name='Other suggestion for college development'),
        ),
    ]
